---
- name: Create a new RHEL VM on an ESXi host
  hosts: localhost
  gather_facts: no
  vars_files:
    - vcenter_vars.yml

  tasks:
  - name: Create a new RHEL VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      folder: "/{{ datacenter }}/vm"
      name: "{{ vm_name }}"
      state: poweredon
      guest_id: rhel7_64Guest
      disk:
      - size_gb: "{{ vm_disk_size }}"
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpu }}"
        boot_firmware: bios
        scsi: paravirtual
      cdrom:
        type: iso
        iso_path: "[{{ datastore }}] {{ iso_folder }}/{{ iso_name }}"
      networks:
      - name: "{{ network }}"
        device_type: vmxnet3
      wait_for_ip_address: yes
    register: new_vm