---
- name: Create new VMs on an ESXi server
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Create new VMs on ESXi
      vmware_guest:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        folder: '{{ vm_folder }}'
        name: "{{ item.name }}"
        state: '{{ vm_state }}'
        # datacenter: '{{ vm_datacenter }}'
        cluster: '{{ vm_cluster }}'
        resource_pool: '{{ vm_resource_pool }}'
        datastore: '{{ vm_datastore }}'
        guest_id: '{{ vm_guest_id }}'
        disk:
          - size_gb: "{{ item.disk_size_gb }}"
            type: '{{ vm_disk_type }}'
            datastore: '{{ vm_datastore }}'
        hardware:
          memory_mb: "{{ item.memory_mb }}"
          num_cpus: "{{ item.num_cpus }}"
          scsi: '{{ vm_scsi }}'
        networks:
          - name: '{{ vm_network }}'
            device_type: '{{ vm_nic }}'
        customization:
          hostname: "{{ item.name }}"
      loop: "{{ vms }}"
      register: deploy
